- .travis.yml
> RDM-1952 Introduce travis

- karma.conf.js
- package.json
- src/app/core/http/http-error.service.spec.ts
- src/app/core/http/http-error.service.ts
- src/app/shared/palette/money-gbp/read-money-gbp-field.component.ts
- src/app/shared/utils/fields.utils.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-1965
- Backend validation errors are displayed correctly when content-type header return extra information
- Currency pipe is updated to use new Angular 5 parameter set
- Mocha test reporter is added for pretty test reports
```
[ ] Yes
[X] No
```
> RDM-1965 3 main tasks are done

- .github/PULL_REQUEST_TEMPLATE.md
> include-cross-browser-testing-on-pull-request-template

- infrastructure/main.tf
- infrastructure/variables.tf
N/A
I wish I could tell
```
[x] Yes
[ ] No
```
> One more time

- infrastructure/aat.tfvars
> One more time FGBhQbmPwH8

- infrastructure/aat.tfvars
> Rollback :(

- src/app/core/auth/oauth2.service.ts
N/A
Strip `https://` from redirect URI; this will be added back by the gateway before submitting to IDAM
```
[ ] Yes
[x] No
```
> Strip `https://` from redirect URI

- infrastructure/aat.tfvars
N/A
CNP use preprod config for AAT
```
[ ] Yes
[x] No
```
> CNP use preprod config for AAT

- infrastructure/main.tf
- infrastructure/variables.tf
- package.json
```
The change is to introduce  way for the project to access values important /
to the execution of automated scripts, in a way that these values are not /
exposed to the public or reference directly by the project code /
A method has been added to main.tf which enables the retrieval /
of those secrets which can then be set as environment variables  /
and supporting varibales added to variables.tf
The smoke tests are now disable to enabled the project to build on CNP 
```
```
[ ] Yes
[x] No
```
> add-vault-to-project

- infrastructure/variables.tf
N/A
Default must be provided for gateway URL. Default set to empty string to match ternary expectation.
```
[ ] Yes
[x] No
```
> Config: Default to blank gateway URL

- Jenkinsfile_CNP
- test/end-to-end/specs/login/login.ccd.spec.js
```
This change is to instruct Jenkins to set some environment variables used by the smoke tests. 
```
```
[ ] Yes
[x] No
```
> Set jenkins environment variables for tests

- Jenkinsfile_CNP
Back out change to CNPJenkins
```
[ ] Yes
[x ] No
```
> back-out-change-to-CNPJenkins

- Jenkinsfile_CNP
Adding cnp value config to Jenkins CNP pipeline
```
[ ] Yes
[x] No
```
> Jenkins cnp vault config

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/prod.tfvars
- src/app/shared/palette/document/document-url.pipe.spec.ts
- src/app/shared/palette/document/document-url.pipe.ts
https://tools.hmcts.net/jira/browse/RDM-1961
Update configuration to support CNP DM.
Add support for pattern replacement in documents URL to support legacy and CNP documents URL.
```
[ ] Yes
[x] No
```
> RDM-1961 Switch to CNP DM 

- Jenkinsfile_CNP
disable vault values loading on cnp Jenkins pipeline
```
[ ] Yes
[x ] No
```
> disable-vault-loading-on-jenkinscnp

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/prod.tfvars
N/A
Support HTTP URIs for documents
```
[ ] Yes
[x] No
```
> Allow HTTP for document URIs

- Jenkinsfile_CNP
> Revert Vault changes breaking the build

- infrastructure/main.tf
Source for associated value code was incorrect.
```
[ ] Yes
[x] No
```
> change-vault-source-location

- infrastructure/main.tf
- infrastructure/variables.tf
N/A
Enable DM CNP support for Sandbox
```
[ ] Yes
[x] No
```
> Add support for Sandbox DM CNP

- src/app/cases/viewer/case-viewer.component.html
- src/app/cases/viewer/case-viewer.component.spec.ts
- src/app/cases/viewer/case-viewer.component.ts
- src/app/core/cases/case-tab.model.ts
- src/app/shared/conditional-show/conditional-show.model.spec.ts
- src/app/shared/conditional-show/conditional-show.model.ts
- src/app/shared/utils/fields.utils.ts
- stubs/unit/aggregated.api.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-1831
This one is adding conditional hide/show for the CaseViewTabs and Fields on the tabs
The case can be tested using the stubs-unit application
```
[ ] Yes
[X] No
```
> Rdm 1964 - Conditional Hide/Show Tabs & TabFields while viewing case

- Dockerfile
> Dist folder is not found

- infrastructure/main.tf
- package.json
- yarn.lock
N/A
This is responsible for introducing vulnerability https://nodesecurity.io/advisories/577 by
```
case-management-web@1.2.0 > npm@5.8.0 > cli-table2@0.2.0 >  lodash@3.10.1 
```
```
[ ] Yes
[x] No
```
> Remove dependency on NPM

- package.json
Bumped up toolkit version
```
[ ] Yes
[ x] No
```
> bump_up_toolkit

- src/app/shared/palette/complex/read-complex-field-raw.component.spec.ts
- src/app/shared/palette/complex/read-complex-field-raw.html
- src/app/shared/palette/complex/read-complex-field-raw.scss
> Add labels to Complex Types raw rendering

- package.json
- src/app/core/profile/profile.model.ts
- src/app/core/profile/profile.test.fixture.ts
https://tools.hmcts.net/jira/browse/RDM-2209
Prepare migration to strategic IDAM by converting user ID to string.
```
[ ] Yes
[x] No
```
> RDM-2209: Convert user ID to string

- src/app/shared/case-editor/case-edit.component.spec.ts
- src/app/shared/case-editor/case-edit.component.ts
- src/app/shared/conditional-show/conditional-show-registrar.service.spec.ts
- src/app/shared/conditional-show/conditional-show-registrar.service.ts
- src/app/shared/conditional-show/conditional-show.directive.spec.ts
- src/app/shared/conditional-show/conditional-show.directive.ts
- src/app/shared/conditional-show/conditional-show.module.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-2208
This one is for fixing mandatory fields preventing to continue when a child field of a complex field is hidden.
```
[ ] Yes
[X] No
```
> Rdm 2208 - Previously entered data is retained and the 'Continue' button is disabled

- infrastructure/saat.tfvars
- src/app/core/auth/oauth2.service.ts
https://tools.hmcts.net/jira/browse/RDM-2246
RDM-2246 Point SAAT to S-IDAM
```
[ ] Yes
[x] No
```
> RDM-2246 Point SAAT to S-IDAM

- infrastructure/preview.tfvars
> Add configuration for preview environment

- package.json
> Bump up case-ui-toolkit version

- src/app/shared/palette/collection/collection-field.scss
- src/app/shared/palette/complex/write-complex-field.component.spec.ts
- src/app/shared/palette/complex/write-complex-field.component.ts
https://tools.hmcts.net/jira/browse/RDM-2469
Improved the display of collection items
```
[ ] Yes
[x] No
```
> [PREVIEW] RDM-2469: Improved the display of collection items

- src/app/search/search.component.spec.ts
- src/app/search/search.component.ts
- src/app/shared/case-editor/label-substitution.service.ts
- src/app/workbasket/workbasket.component.spec.ts
- src/app/workbasket/workbasket.component.ts
https://tools.hmcts.net/jira/browse/RDM-626
Search filter component and search component changed to support search on metadata fields. Have retained some code to support search based on state for the case list component.
Depends on
hmcts/ccd-definition-store-api#94
hmcts/ccd-data-store-api#141
```
[ ] Yes
[ ] No
```
> NEW - RDM-1240/RDM-626 - search cases by metadata

- src/app/cases/viewer/case-viewer.component.spec.ts
- src/app/cases/viewer/case-viewer.component.ts
https://tools.hmcts.net/jira/browse/RDM-2601
Fix overridding of case field by metadata for show condition evaluation
```
[ ] Yes
[x] No
```
> Fix/RDM-1240: Fix show condition on case view

- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RDM-2311
```
[ ] Yes
[ ] No
```
> Nightly: build on the nightly pipeline

- server.ts
RDM-2253
Import of non-es6 dependency was incorrect.
```
[ ] Yes
[x] No
```
> [PREVIEW] RDM-2253: Fix import of x-frame-options

- src/app/oauth2/oauth2-redirect.component.spec.ts
- src/app/oauth2/oauth2-redirect.component.ts
https://tools.hmcts.net/jira/browse/RDM-2700
Redirect to login page when oauth code is missing
```
[ ] Yes
[x] No
```
> [PREVIEW] RDM-2700: Redirect after password reset

- src/public/config.json
Fix the problem in master
```
[x] Yes
[ ] No
```
> [PREVIEW] Fix the compilation error'

- package.json
- src/app/app.module.ts
- src/app/shared/palette/collection/write-collection-field.component.spec.ts
- src/app/shared/palette/collection/write-collection-field.component.ts
- src/app/shared/palette/collection/write-collection-field.html
- src/app/shared/remove-dialog/remove-dialog.component.spec.ts
- src/app/shared/remove-dialog/remove-dialog.component.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-2414
When new item added is collection:
* Scroll to new item if added with top Add button
* Focus first input field of newly added item
```
[ ] Yes
[x] No
```
> [PREVIEW] RDM-2414: Improve behaviour on collection add

- package.json
Disable smoke tests
```
[ ] Yes
[x] No
```
> disable-smoke-tests

- src/app/shared/search/search-result.html
> Demo update -- Ability to configure first column of case list page 

- src/app/search/search.component.html
- src/app/search/search.component.ts
- src/app/shared/search/search-result.component.spec.ts
- src/app/shared/search/search-result.component.ts
- src/app/workbasket/workbasket.component.html
- src/app/workbasket/workbasket.component.spec.ts
- src/app/workbasket/workbasket.component.ts
https://tools.hmcts.net/jira/browse/RDM-2776
Code changes to fix bug on pagination when metadata filters are used on search
```
[ ] Yes
[x] No
```
> RDM-2776 - pagination bug fix for metadata filters

- src/app/cases/viewer/case-viewer.component.html
- src/app/cases/viewer/case-viewer.component.spec.ts
- src/app/cases/viewer/case-viewer.scss
- src/app/shared/event-log/event-log-details.html
- src/app/shared/event-log/event-log-table.html
- src/app/shared/event-log/event-log.html
- src/app/shared/header/case-header.html
- src/app/shared/palette/complex/read-complex-field-table.component.spec.ts
- src/app/shared/palette/complex/read-complex-field-table.html
- src/app/shared/palette/complex/read-complex-field-table.scss
- src/style/app.scss
https://tools.hmcts.net/jira/browse/RDM-1866
Font should be GDS Transport font throughout
```
[ ] Yes
[x] No
```
> [PREVIEW] RDM-1866_1: Fonts throughout

- src/app/cases/creator/filters/create-case-filters.component.spec.ts
- src/app/cases/creator/filters/create-case-filters.component.ts
- src/app/core/core.component.spec.ts
- src/app/core/definitions/definitions.service.spec.ts
- src/app/search/search.component.spec.ts
- src/app/shared/domain/definition/jurisdiction.model.ts
- src/app/shared/search/filters/search-filters.component.spec.ts
- src/app/shared/search/filters/search-filters.component.ts
- src/app/shared/search/search-result.component.spec.ts
- src/app/workbasket/filters/workbasket-filters.component.spec.ts
- src/app/workbasket/filters/workbasket-filters.component.ts
- src/app/workbasket/workbasket.component.spec.ts
- stubs/unit/aggregated.api.json
- stubs/unit/aggregated.routes.json
- yarn.lock
Reverts hmcts/ccd-case-management-web#264
> Revert "RDM-2923 Make retrieval of Case Types faster in Search filters"

- src/app/cases/creator/filters/create-case-filters.component.spec.ts
- src/app/cases/creator/filters/create-case-filters.component.ts
- src/app/core/core.component.spec.ts
- src/app/core/definitions/definitions.service.spec.ts
- src/app/search/search.component.spec.ts
- src/app/shared/domain/definition/jurisdiction.model.ts
- src/app/shared/search/filters/search-filters.component.spec.ts
- src/app/shared/search/filters/search-filters.component.ts
- src/app/shared/search/search-result.component.spec.ts
- src/app/workbasket/filters/workbasket-filters.component.spec.ts
- src/app/workbasket/filters/workbasket-filters.component.ts
- src/app/workbasket/workbasket.component.spec.ts
- stubs/unit/aggregated.api.json
- stubs/unit/aggregated.routes.json
- yarn.lock
Reverts hmcts/ccd-case-management-web#267
> [PREVIEW] Revert "Revert "RDM-2923 Make retrieval of Case Types faster in Search filters""

- package.json
- test/config/smoke.conf.js
> [PREVIEW] Update package.json

- README.md
- package.json
- test/config/smoke.conf.js
> [PREVIEW] Build artifacts

- src/app/shared/search/filters/search-filters.component.spec.ts
- src/app/shared/search/filters/search-filters.component.ts
- src/app/workbasket/filters/workbasket-filters.component.ts
- yarn.lock
Altered search filters behaviour. Now 1st case-type in the list is selected by default
```
[ ] Yes
[X] No
```
> [PREVIEW] Search filter selects the first case-type & removed unused imports

- README.md
- src/app/shared/domain/draft.ts
- src/app/shared/search/search-result.component.spec.ts
- src/app/shared/search/search-result.component.ts
- src/app/shared/search/search-result.html
- src/app/shared/utils/case-reference.pipe.ts
> Case ref test

- src/app/shared/search/search-result.html
> Merging hyphenation from RDM-2964 into RDM-900

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-2635
```
[ ] Yes
[x] No
```
> [PREVIEW] Infra: specific ASP resource group

- infrastructure/main.tf
/site - 100M
/LogFiles - 400M
Fixes RDM-2366
https://tools.hmcts.net/jira/browse/RDM-2366
```
[X] Yes
[ ] No
```
> Set local cache to 500 MB

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-3082
```
[ ] Yes
[x] No
```
> Remove default node version since d638cb0e

- .dockerignore
- .snyk
- Dockerfile
- Jenkinsfile_CNP
- package.json
https://tools.hmcts.net/jira/browse/RDM-3046
```
[ ] Yes
[x] No
```
> Enable Docker build in pipeline

- test/functional-tests/config/conf.js
- test/page-objects/login.po.js
> [PREVIEW] timeout hotfix for tests

- test/page-objects/login.po.js
> fix broken smoke tests

- test/functional-tests/pageObjects/caseListPage.js
> Front end test fix - ignore Synchronization

- Jenkinsfile_nightly
- test/config/crossbrowser.conf.js
> Run Saucelabs nightly

- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RDM-3275
```
[ ] Yes
[x] No
```
> Make crossBrowser test run optional

- package.json
Disabling Smoke and enabling Preview to see if Functional has the same problem
```
[ ] Yes
[X ] No
```
> [PREVIEW] Disabling Smoke

- package.json
> Enable Smoke Tests

- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-2789
```
[ ] Yes
[ ] No
```
> Sync yarn.lock with package.json

- package.json
- yarn.lock
This is a change to update ccd-case-management-web to use a new version of the ccd-case-ui-toolkit which introduces the ability to link cases together by case reference. 
```
[x] Yes
[ ] No
```
> [Preview] update-to-use-version-2.6.0-of-ccd-case-ui-toolkit

- src/app/shared/search/search-result.scss
- src/app/workbasket/workbasket.scss
https://tools.hmcts.net/jira/browse/RDM-3438
Fixing the Create new case button issue
```
[ ] Yes
[x] No
```
> [PREVIEW] RDM-3438: Create new case button fix

- package.json
- src/app/cases/creator/create-case-event-trigger.resolver.spec.ts
- src/app/cases/creator/create-case-event-trigger.resolver.ts
- yarn.lock
DO NOT MERGE BEFORE [ccd-case-ui-toolkit](https://github.com/hmcts/ccd-case-ui-toolkit/pull/148)
https://tools.hmcts.net/jira/browse/RDM-3427
UI Toolkit: Use Start Event API v2
```
[ ] Yes
[x] No
```
> RDM-3427 UI Toolkit: Use Start Event API v2

- test/functional-tests/features/caseCreation.feature
- test/functional-tests/features/checkYourAnswers.feature
- test/functional-tests/pageObjects/basePage.js
- test/functional-tests/pageObjects/caseListPage.js
- test/functional-tests/pageObjects/createCaseStartPage.js
- test/functional-tests/pageObjects/createCaseWizardPage.js
- test/functional-tests/pageObjects/webdriver-components/dropdown.js
- test/functional-tests/stepDefinitions/create-caseSteps.js
- test/functional-tests/stepDefinitions/loginSteps.js
Functional Tests for Check Your Answers
```
[ ] Yes
[x] No
```
> tests for check your answers

- package.json
- yarn.lock
RDM-2009 ComplexType element (non-collection) in Labels (with markdown) & show/hide
Increments the version of ccd-case-ui-toolkit to enable ComplexType element (non-collection) in Labels (with markdown) & show/hide
> rdm-2009-update-toolkit-version

- package.json
- src/app/cases/creator/create-case-event-trigger.resolver.spec.ts
- src/app/cases/creator/create-case-event-trigger.resolver.ts
- src/app/cases/event-trigger/event-trigger.resolver.spec.ts
- src/app/cases/event-trigger/event-trigger.resolver.ts
- src/public/config.json
- yarn.lock
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDM-3512
Change description
Consume new V2 endpoint.
Merge this after [ccd-data-store-api](https://github.com/hmcts/ccd-data-store-api/pull/271) and after releasing [case-ui-toolkit](https://github.com/hmcts/ccd-case-ui-toolkit/pull/175)
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
> RDM-3512 Implement internal Get Trigger for Draft endpoint in API v2

- Jenkinsfile_CNP
- test/functional-tests/features/conditionalLogic.feature
- test/functional-tests/features/fieldTypes.feature
- test/functional-tests/pageObjects/basePage.js
- test/functional-tests/pageObjects/caseDetailsPage.js
- test/functional-tests/pageObjects/createCaseWizardPage.js
- test/functional-tests/pageObjects/webdriver-components/button.js
- test/functional-tests/stepDefinitions/baseSteps.js
- test/functional-tests/stepDefinitions/caseDetailsSteps.js
- test/functional-tests/stepDefinitions/create-caseSteps.js
- test/functional-tests/stepDefinitions/cyaSteps.js
- test/functional-tests/stepDefinitions/definitionFileSteps.js
- test/functional-tests/stepDefinitions/loginSteps.js
- test/functional-tests/stepDefinitions/testSetup.js
- test/functional-tests/stepDefinitions/validationSteps.js
- tests around show and hide / conditional logic
- split step files
```
[ ] Yes
[x] No
```
> Conditional functional tests

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- infrastructure/outputs.tf
https://tools.hmcts.net/jira/browse/RDM-2931
```
[ ] Yes
[ ] No
```
> [PREVIEW] Use new secret loading structure

- package.json
- yarn.lock
> Revert toolkit version to 2.19.1

- infrastructure/sprod.tfvars
RDM-3570
Give SProd its rightful hostname to replicate Prod config.
```
[ ] Yes
[x] No
```
> RDM-3570: Set SProd hostname

- src/app/app.config.spec.ts
- src/app/app.config.ts
- src/app/core/cases/case-history.service.spec.ts
- src/app/core/cases/case-history.service.ts
- src/app/shared/case-history/case-history.resolver.spec.ts
- src/app/shared/case-history/case-history.resolver.ts
- src/app/workbasket/workbasket-input-filter.service.spec.ts
When data-store is ready we can merge the original Rdm-3565 story
> Revert "Revert "Rdm 3565 UI Toolkit: Use Get CaseHistoryForEvent API v2""

- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-2618
```
[ ] Yes
[x] No
```
> Use shared app insight

- src/app/shared/search/search-result.scss
- src/app/workbasket/filters/workbasket-filters.component.spec.ts
- src/app/workbasket/filters/workbasket-filters.component.ts
- src/app/workbasket/filters/workbasket-filters.html
https://tools.hmcts.net/jira/browse/RDM-2752
Provide Any option in the State Field for CaseList
```
[ ] Yes
[x] No
```
> [PREVIEW] RDM-2752: Provide Any option in the State Field for CaseList

- .travis.yml
- Dockerfile
- package.json
https://tools.hmcts.net/jira/browse/RDM-3320
```
[ ] Yes
[ ] No
```
> Update yarn minimum version

- infrastructure/aat.tfvars
https://tools.hmcts.net/jira/browse/RDM-3860
Use update DNS for ccd-api-gateway in AAT: https://gateway-ccd.aat.platform.hmcts.net
```
[ ] Yes
[x] No
```
> RDM-3860: Update gateway DNS in AAT

- charts/ccd-case-management-web/requirements.yaml
- charts/ccd-case-management-web/values.aat.template.yaml
- charts/ccd-case-management-web/values.template.yaml
https://tools.hmcts.net/jira/browse/RDM-3855
```
[ ] Yes
[ ] No
```
> Remove Helm alias

- package.json
- src/app/cases/creator/filters/create-case-filters.component.spec.ts
- yarn.lock
> Demo toolkit update

- infrastructure/saat.tfvars
> Enable SAAT with SIDAM

- Dockerfile
- hub.Dockerfile
https://tools.hmcts.net/jira/browse/RDM-4058
```
[ ] Yes
[ ] No
```
> Create Docker hub Dockerfile

- README.md
- bin/runFunctionalTests.sh
- bin/runSmokeTests.sh
- test/config/conf.js
- test/features/conditionalLogic.feature
Run functional tests in parallel to reduce execution time
add tests that were disabled due to protractor bug
link to test docs from main docs
disable tests on preview
```
[ ] Yes
[x] No
```
> run tests in parallel

- package.json
- yarn.lock
RDM-4009
Consume v2 search endpoint 
```
[ ] Yes
[x] No
```
> Consume Search V2 API endpoint

- package.json
- yarn.lock
RDM-3471
RDM-3472
RDM-3473
```
[ ] Yes
[x ] No
```
> Toolkit version update to 2.32.0

- package.json
- yarn.lock
RDM-2788
flexible case history tab
```
[ ] Yes
[x] No
```
> Consume toolkit v2.33 - flexible case history tab

- charts/ccd-case-management-web/values.aat.template.yaml
changing Helm charts IDAM  to look at SIDAM instance instead
> Switch AAT to SIDAM

- infrastructure/demo.tfvars
Switch Demo to look at AAT SIDAM
> SIDAM idam_authentication_web_url

- package.json
- yarn.lock
RDM-4184 - Remove history tab
```
[ ] Yes
[X] No
```
> updated toolkit version

- package.json
- yarn.lock
> Update toolkit version

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-4591
Fixing the special character issue in regex expression
```
[ ] Yes
[x] No
```
> RDM-4591: Toolkit version updated

- charts/ccd-case-management-web/requirements.yaml
- package.json
- src/app/core/core.module.ts
- src/app/workbasket/filters/workbasket-filters.component.spec.ts
- src/app/workbasket/filters/workbasket-filters.component.ts
- src/app/workbasket/filters/workbasket-filters.html
- src/app/workbasket/filters/workbasket-filters.scss
- src/app/workbasket/workbasket-input-filter.service.spec.ts
- src/app/workbasket/workbasket-input-filter.service.ts
- src/app/workbasket/workbasket-input.model.ts
- src/app/workbasket/workbasket.component.html
- src/app/workbasket/workbasket.component.spec.ts
- src/app/workbasket/workbasket.component.ts
- src/app/workbasket/workbasket.module.ts
- yarn.lock
Reverts hmcts/ccd-case-management-web#658
> Revert "Rdm 4535 new contract"

- package.json
- yarn.lock
> Rdm 4264 DAC - Duplicate postcode input IDs

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-4512
```
[ ] Yes
[x] No
```
> RDM-4512: Updated ui-toolkit version to 2.55.2

- test/README.md
- test/config/conf.js
- test/config/crossbrowser.conf.js
- test/config/local.conf.js
https://tools.hmcts.net/jira/browse/RDM-5214
Funct tests config fix
```
[ ] Yes
[X ] No
```
> RDM-5214 Config fix to pick up feature files from directories

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-5175
Upgrade Tomcat version to 9
```
[ ] Yes
[X] No
```
> bump up tomcat version to 9

- package.json
- yarn.lock
RDM-4891
```
[ ] Yes
[X] No
```
> RDM-4891 - New Postcode Lookup 

- charts/ccd-case-management-web/Chart.yaml
- charts/ccd-case-management-web/requirements.yaml
- charts/ccd-case-management-web/values.aat.template.yaml
- charts/ccd-case-management-web/values.preview.template.yaml
- charts/ccd-case-management-web/values.template.yaml
- charts/ccd-case-management-web/values.yaml
https://tools.hmcts.net/jira/browse/RDM-5211
IDAM redirect url for PR environments
https://tools.hmcts.net/confluence/display/SISM/AKS+set+up+for+service+applications+PRs
```
[ ] Yes
[ x] No
```
> RDM-5211 - using idam-pr chart to add redirect url for PRs

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-4525
Remove unused id on write fixed list field
```
[ ] Yes
[X] No
```
> Remove unused id on write fixed list field

- package.json
- yarn.lock
Updating case-management-web with the following ui-toolkit fixes:
RDM-4266
RDM-4282
RDM-4274
```
[ ] Yes
[x ] No
```
> DAC Fixes - Bumped up ui-toolkit version

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-5168
Fix submitted callback 
https://github.com/hmcts/ccd-case-ui-toolkit/pull/389
https://github.com/hmcts/ccd-data-store-api/pull/495
```
[ ] Yes
[X] No
```
> RDM-5168 - submitted Callback fix 

- package.json
- yarn.lock
> RDM-4279 - Bumped up toolkit release to 2.58.5

- package.json
- yarn.lock
> RDM-5044 - Bumped up toolkit version to 2.58.6

- Dockerfile
- Jenkinsfile_CNP
- acb.tpl.yaml
- charts/ccd-case-management-web/values.yaml
- docker-compose.yml
docker registry update
```
[ ] Yes
[ x] No
```
> updating references according to docker registry change

- package.json
- src/app/cases/creator/case-creator-submit.component.spec.ts
- yarn.lock
Reverts hmcts/ccd-case-management-web#564
> Revert "RDM-4073 Changes for conforming with CaseField updates"

- charts/ccd-case-management-web/Chart.yaml
- charts/ccd-case-management-web/requirements.yaml
- charts/ccd-case-management-web/templates/NOTES.txt
- charts/ccd-case-management-web/values.yaml
> updated Chart

- package.json
- src/style/app.scss
- yarn.lock
Reverts hmcts/ccd-case-management-web#769
> Revert "Rdm 5398"

- charts/ccd-case-management-web/Chart.yaml
- charts/ccd-case-management-web/requirements.yaml
> Upgrade idam pr version

- package.json
- test/features/media-viewer.feature
> reenable functional tests

- charts/ccd-case-management-web/Chart.yaml
- charts/ccd-case-management-web/requirements.yaml
> Bumping to latest chart

- charts/ccd-case-management-web/values.preview.template.yaml
- package.json
- test/features/search.feature
- yarn.lock
> RDM-6887: Bumped up toolkit version

- package.json
- yarn.lock
> Force resolution of util and assert

- src/polyfills.ts
https://tools.hmcts.net/jira/browse/RDM-7377
Resolve issue with deformed UI elements in IE
```
[ ] Yes
[x] No
```
> RDM-7377 - IE11 deformed UI elements

- src/app/core/core.component.spec.ts
- src/app/core/core.component.ts
- src/app/core/core.module.ts
- src/app/shutter/shutter.component.ts
- src/app/shutter/shutter.module.ts
https://tools.hmcts.net/jira/browse/RDM-7293
Use internal/external translator for banner and shutter URLs
```
[ ] Yes
[x] No
```
> RDM-7293 - Use internal/external translator for banner and shutter URLs

- charts/ccd-case-management-web/values.preview.template.yaml
- package.json
- src/app/shutter/shutter.component.html
- src/app/shutter/shutter.component.ts
- test/pageObjects/ccd-components/globalNavBar.js
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-7524
Wording changes for shuttering logic
```
[ ] Yes
[ X] No
```
> Rdm 7524: Wording Updates to CCD Shuttering and Redirection to Expert UI

- src/app/footer-nav/contact-us.component.html
https://tools.hmcts.net/jira/browse/RDM-7459
Update CTSC details
```
[ ] Yes
[x] No
```
> RDM-7459 - Update CTSC details

- infrastructure/ithc.tfvars
> RDM-7695 Update-IDAM-URLs

- Dockerfile
- Jenkinsfile_CNP
- charts/ccd-case-management-web/Chart.yaml
- charts/ccd-case-management-web/requirements.yaml
- charts/ccd-case-management-web/values.aat.template.yaml
- charts/ccd-case-management-web/values.preview.template.yaml
- charts/ccd-case-management-web/values.yaml
- yarn.lock
#JIRA link (if applicable) ###
AB#795
Updated values yaml for AKS migration
```
[ ] Yes
[x] No
```
> Migrate to aks

- charts/ccd-case-management-web/Chart.yaml
- charts/ccd-case-management-web/requirements.yaml
> RDM-7867-Update-base-chart

- test/pageObjects/loginPage.js
This reverts commit 03b9bec3 because it turned out it's not working in fixing the flaky builds
> Revert "fix flaky func tests on login page: (#900)"

- test/pageObjects/webdriver-components/dropdown.js
> fix for test

- infrastructure/demo.tfvars
https://tools.hmcts.net/jira/browse/RDM-7932
CCD Print URL doesn't work correctly on Demo
```
[ ] Yes
[ x] No
```
> RDM-7932 - demo print url update

- charts/ccd-case-management-web/Chart.yaml
- charts/ccd-case-management-web/values.yaml
> Update dm url remote

- test/features/caseUpdate.feature
https://tools.hmcts.net/jira/browse/RDM-7986
Reenable smoke and functional tests
```
[ ] Yes
[X] No
```
> re-enable the temporarily disabled test

- Jenkinsfile_CNP
> AKS prod migration

- src/app/core/core.component.spec.ts
- src/app/core/core.component.ts
- src/app/workbasket/workbasket.component.spec.ts
- src/app/workbasket/workbasket.component.ts
https://tools.hmcts.net/jira/browse/RDM-7924
Handle profile not having workbasket defaults
```
[ ] Yes
[ X] No
```
> Rdm-7924: Handle no user profile in the front end

- charts/ccd-case-management-web/values.preview.template.yaml
> Remove Custom Preview URLs and restore defaults

- package.json
- src/app/mv-wrapper/media-viewer-wrapper.component.html
- yarn.lock
> RDM-8348 Media Viewer Upgrade

- Jenkinsfile_CNP
- charts/ccd-case-management-web/Chart.yaml
- charts/ccd-case-management-web/requirements.yaml
related to: https://github.com/hmcts/chart-idam-pr/pull/22
> Update idam-pr chart version

- charts/ccd-case-management-web/Chart.yaml
- package.json
> Skip smokes to enable build

- Jenkinsfile_CNP
> remove installCharts

- charts/ccd-case-management-web/Chart.yaml
- charts/ccd-case-management-web/values.yaml
https://tools.hmcts.net/jira/browse/RDM-10469
adjust autoscaling
```
[ ] Yes
[X] No
```
> adjust autoscaling

- charts/ccd-case-management-web/Chart.yaml
- charts/ccd-case-management-web/values.yaml
> raise the autoscale range based on latest slowness news

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-10962
Downgraded the ccd-case-ui-toolkit version to revert back RDM-8661 changes
```
[ ] Yes
[x] No
```
> RDM-10962: Document uploads not enabling continue button on CCD

- config/default.yaml
- server.ts
- src/public/config.json
> Role name corrected

- config/default.yaml
- server.ts
- src/public/config.json
NA
temporary changes to test AI in preview
```
[ ] Yes
[x] No
```
> Disabled AI

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-11464
Advisory-1638 (CCD Case Man Web)
```
[ ] Yes
[X] No
```
> RDM-11464 Advisory-1638 (CCD Case Man Web)

- Dockerfile
https://tools.hmcts.net/jira/browse/RDM-12109
Removed directory name from COPY command
```
[ ] Yes
[x] No
```
> RDM-12109: Remove directory name from COPY command

- Dockerfile
Reverts hmcts/ccd-case-management-web#1050
> Revert "RDM-12109: Remove directory name from COPY command"

- charts/ccd-case-management-web/values.preview.template.yaml
> revert to dev to dev wiring

- Dockerfile
- charts/ccd-case-management-web/values.preview.template.yaml
- package.json
https://tools.hmcts.net/jira/browse/CCD-365
Removed the directory usage from COPY command
```
[ ] Yes
[x] No
```
> RDM-12109: Fortify Issue 13318199 - Dockerfile

- package.json
- yarn.lock
> force underscore version
